Que1:-Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
      enhance Python's capabilities for numerical operations?
Ans: It Helps You Conduct Working in Scientific Computing and Data Analysis, as NumPy/Object-Oriented Programming The 
    Uses of Object-oriented programming reduces recursion etc;NumPy is a commonly used library for N-dimensional array 
    creation in Python which can be utilized to perfrom numpy operations and much more. You can use it to extend the 
    functionality of Python, doing computationally intensive numerical computations (needed for scientific data             analysis) in an efficient way. 
    
    Benefits of using NumPyPerformance : NumPy arrays (ndarrays) are more compact than Python lists, and 
    this type of data structure is more efficient in terms for operations like element-wise addition or multiplication.     Thisresults in over much faster operations on arrays thanks to the C implementation.
    
    Vectorization: In NumPy operations are esentially inherited but applied element-wise to arrays,requiring no need of
    explicit loops.
    
    Integration: NumPy plays well with scientific libraries such as SciPy, Matplotlib and Pandas which is why it has a       firm foothold in the scientific Python ecosystem.
    
    Extensive Capabilities — it offers for use mathematical operations, linear algebra and random number generation         among  many other built-in functions which makes the package versatile to support a wide array of applications.

Que2:-Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
Ans:- Comparing `np. mean()` and `np. average()` in NumPy:
- `np. mean()`: Compute the arithmetic mean along the specified axis. It just adds the elements and divide it with
   number of element.

- `np. average()` – Calculates the average of elements for some other axis, but unlike mean() here we can calculate 
   weighted averages. If no weights are given, it behaves like np. mean()`. It computes a mean value, but if weights are
   given, it will be calculated as the weighted average.

- When to use: Use `np. mean()` when you mean basic average. Use `np. average() is similar to average() with the ability
   to handle different weights for each element in a AIm pair.
    

In [4]:
# Que3:- Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# Ans:-1D Array: By Slicing you can reverse a 1D array following by :5
import numpy as np
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]
reversed_arr


array([4, 3, 2, 1])

In [5]:
# 2D Array- In the case of 3d we can reverse using slicing along any direction.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr[::-1, :]
reversed_rows 

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [6]:
# Reversing columns:
reversed_cols = arr[:, ::-1]
reversed_cols

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [7]:
# Reversing both rows and columns
fully_reversed = arr[::-1, ::-1]
fully_reversed

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [9]:
# Que4:- How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance.
# Ans:- You can see the type of data stored in a NumPy array with its `dtype` attribute.
arr = np.array([1, 2, 3])
data_type = arr.dtype
data_type


dtype('int64')

Importance of Data Types:-

Memory Management: Data Types require different amount of memory. Choosing the right data type will help in proper
memory management.
Performance—Some operations are more аble to be optimized with particular data types. To put numbers on my prior 
statement, `float32` is faster in computational terms than `float64`, for instance floating-points operations.

Que5:-Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans:-The Basics of NumPy Defining `ndarrays` and Their Key Features-
    An ndarray is the core data structure in NumPy, consisting of a multi-dimensional table(array) with homogeneous          elements.
    - Key Features:-

    -homogeneity (all elements have the same data type)
    Storage: ndarrays are usually stored as contiguous blocks of memory, which makes them fast to access and process.
    Vectorized Operations: That is, they occur element-by-element and are aimed to run as efficiently.
    Note that, it is a valid statement because while `ndarrays` are similar to Python lists they have the property of       being  fixed in size and like homogeneous in data type except for `object`, which hence allows more efficient           mathematical operations.

Que6:- Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans:-NumPy arrays are significantly faster than Python lists for large-scale numerical operations due to:
    Contiguous Memory Layout: NumPy arrays are stored in contiguous memory, reducing the overhead of data access.
    Vectorization: Operations are implemented in compiled C code and applied element-wise, avoiding the need for explicit loops.
    Less Memory Overhead: NumPy arrays have less memory overhead compared to Python lists since they store elements of the same type and size.

In [10]:
# Que7:-Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.
# Ans:-vstack(): Stacks arrays vertically (row-wise). It concatenates arrays along the first axis (rows).
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack((a, b))
vstacked

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# hstack(): Stacks arrays horizontally (column-wise). It concatenates arrays along the second axis (columns).
hstacked = np.hstack((a, b))
hstacked


array([1, 2, 3, 4, 5, 6])

In [13]:
# Que8:-Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions.
# Ans:-fliplr(): Flips an array horizontally (left to right). It reverses the order of columns.
arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_lr = np.fliplr(arr)
flipped_lr


array([[3, 2, 1],
       [6, 5, 4]])

In [14]:
# flipud(): Flips an array vertically (upside down). It reverses the order of rows.
flipped_ud = np.flipud(arr)
flipped_ud


array([[4, 5, 6],
       [1, 2, 3]])

In [15]:
# Que:9-Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# Ans:-The array_split() method splits an array into multiple sub-arrays. It handles uneven splits by allowing the last
# few sub-arrays to have fewer elements than the others:

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 4)
split_arr


[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [16]:
# Que10:- Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
# operations?
# ANs:-Vectorization: Refers to the ability to apply operations on entire arrays without the need for explicit loops.
# This leads to more concise and faster code. For example, adding two arrays:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  
c


array([5, 7, 9])

In [ ]:
# Broadcasting: Refers to the ability of NumPy to perform operations on arrays of different shapes. Smaller arrays are 
# "broadcasted" to match the shape of larger arrays when necessary. For example:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
c = a + b 
c


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

Practical Question

In [19]:
# Que1:-Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
# ans-
import numpy as np
arr = np.random.randint(1, 101, size=(3, 3))
transposed_arr = arr.T
transposed_arr  

array([[25, 45, 45],
       [67,  3, 32],
       [12, 39, 83]])

In [20]:
# Que2:-Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
# ans:-
arr = np.arange(10)
arr_2x5 = arr.reshape(2, 5)
# arr_2x5  Display the 2x5 array
arr_5x2 = arr_2x5.reshape(5, 2)
arr_5x2  


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
# Que3:Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
# Ans:-
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
bordered_arr 


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.14235499, 0.33679162, 0.14357883, 0.34561679,
        0.        ],
       [0.        , 0.62252511, 0.95364015, 0.98689374, 0.88645375,
        0.        ],
       [0.        , 0.65455097, 0.43360534, 0.6550823 , 0.87195193,
        0.        ],
       [0.        , 0.86350437, 0.44769931, 0.73084227, 0.7749901 ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [22]:
# Que4:- Using NumPy, create an array of integers from 10 to 60 with a step of 5
# Ans:-
arr = np.arange(10, 61, 5)
arr 

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [23]:
# Que5-:Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.
# Ans:-
arr = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(arr)
upper_case 

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [24]:
lower_case = np.char.lower(arr)
lower_case 

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [25]:
title_case = np.char.title(arr)
title_case  

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [26]:
# Que6:-Generate a NumPy array of words. Insert a space between each character of every word in the array
# Ans:-
arr = np.array(['python', 'numpy', 'pandas'])
spaced_arr = np.char.join(' ', arr)
spaced_arr 

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [28]:
# Que7:-Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# Ans:-
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
addition = arr1 + arr2
addition  

array([[ 6,  8],
       [10, 12]])

In [29]:
subtraction = arr1 - arr2
subtraction 

array([[-4, -4],
       [-4, -4]])

In [30]:
multiplication = arr1 * arr2
multiplication  

array([[ 5, 12],
       [21, 32]])

In [31]:
division = arr1 / arr2
division  

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [32]:
# Que8- Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
# Ans
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
diagonal_elements


array([1., 1., 1., 1., 1.])

In [33]:
# Que9- Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.
# ANs:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
arr = np.random.randint(0, 1001, size=100)
prime_numbers = arr[np.vectorize(is_prime)(arr)]
prime_numbers 

array([409,  83, 397, 257, 569,  71,  11, 269, 659, 547, 149, 227, 227,
       571, 449])

In [ ]:
# Que10-: Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.
Ans:-